package edu.curtin.terminalgriddemo.eventparser;/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DATE = 1;
  /** RegularExpression Id. */
  int TIME = 2;
  /** RegularExpression Id. */
  int NUMBER = 3;
  /** RegularExpression Id. */
  int STRING_LITERAL = 4;
  /** RegularExpression Id. */
  int SPACE = 5;
  /** RegularExpression Id. */
  int NEWLINE = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<DATE>",
    "<TIME>",
    "<NUMBER>",
    "<STRING_LITERAL>",
    "\" \"",
    "\"\\n\"",
    "\"event\"",
  };

}
