/* Generated By:JavaCC: Do not edit this line. MyParserConstants.java */
package edu.curtin.terminalgriddemo.eventparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DATE = 1;
  /** RegularExpression Id. */
  int EVENT = 2;
  /** RegularExpression Id. */
  int PLUGIN = 3;
  /** RegularExpression Id. */
  int SCRIPT = 4;
  /** RegularExpression Id. */
  int TIME = 5;
  /** RegularExpression Id. */
  int NUMBER = 6;
  /** RegularExpression Id. */
  int STRING_LITERAL = 7;
  /** RegularExpression Id. */
  int TEXT = 8;
  /** RegularExpression Id. */
  int LBRACE = 9;
  /** RegularExpression Id. */
  int RBRACE = 10;
  /** RegularExpression Id. */
  int COLON = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int SPACES = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<DATE>",
    "\"event\"",
    "\"plugin\"",
    "\"script\"",
    "<TIME>",
    "<NUMBER>",
    "<STRING_LITERAL>",
    "<TEXT>",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\",\"",
    "<SPACES>",
  };

}
